version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    ports:
     - "5044:5044"
     - "9600:9600"
    volumes:
     - ./conf/logstash/pipeline/:/usr/share/logstash/pipeline/
     - ./conf/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml

  elastic:
    image: elasticsearch:6.4.1
    ports:
     - "9200:9200"
     - "9300:9300"
