version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./conf/logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./conf/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - "5601:5601"
    volumes:
      - ./conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.2
    volumes:
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/var/log/
